Extension { #name : 'TLeModelVisitor' }

{ #category : '*Ensemble-Lepiter' }
TLeModelVisitor >> visitEnsembleBoardSnippet: aSnippet [
	^ self visitSnippet: aSnippet
]

{ #category : '*Ensemble-Lepiter' }
TLeModelVisitor >> visitEnsembleProjectSnippet: aSnippet [
	^ self visitSnippet: aSnippet
]

{ #category : '*Ensemble-Lepiter' }
TLeModelVisitor >> visitEnsembleTaskSnippet: aSnippet [
	^ self visitSnippet: aSnippet
]
